services:
  database:
    container_name: database
    restart: always
    image: postgres

    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "gestao"
      POSTGRES_DB: "gestaoServidores"
      POSTGRES_PASSWORD: "SuperPassword@22"